### ISSUE TITLE
Support for Laravel 7

### ISSUE THREAD

**Issue by Cordar** [Neurony/laravel-duplicate#11]
I've seen there is a pull request from Mar 4 2020 but still no answer. We are trying to upgrade to Laravel 7 but it's not possible atm due to this package.

**Comment by zbiller** [comment]
Hi @Cordar 

Sorry for the long wait, I've been caught up with other stuff.
You can now install this package in your Laravel 7.x projects using the version `4.0.0`

**Comment by Cordar** [comment]
Thanks!
