### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by AugmentBLU** [Neurony/laravel-duplicate#14]
Hello, will you be updating this package to support Laravel 8? 

Thanks!

**Comment by zbiller** [comment]
Hi @AugmentBLU   

Unfortunately this package is now discontinued. 
Please check out [Varbox](https://varbox.io) (Laravel Admin Panel) for this functionality, but much more.

- documentation: [https://varbox.io/docs](https://varbox.io/docs)
- live demo: [https://demo.varbox.test/admin](https://demo.varbox.test/admin)
- repository: [https://github.com/VarboxInternational/varbox](https://github.com/VarboxInternational/varbox)

Thank you!
