### ISSUE TITLE
Include only relations

### ISSUE THREAD

**Issue by rentalhost** [Neurony/laravel-duplicate#3]
Hello.

I like to suggest you to create a way to include only specified relations, so I can specify that I wants to duplicate user, for instance, with phones and addresses only. Even for future new relations, it will just be added to duplication rule if you manually set it.

Thanks!

**Comment by zbiller** [comment]
Hi @rentalhost 

I think what you're asking will come into conflict with the current exclusion logic of relations.

This package's goal is to make it easy to deep duplicate a model record (meaning relations included).

If you have a suggestion on how to implement this without getting people confused what to use (include/exclude) please let me know.

Thanks!
